import asyncio
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from enum import StrEnum
from typing import TYPE_CHECKING

from coolname import generate_slug

from ntrp.agent import Usage
from ntrp.tools.core.context import BackgroundTaskRegistry

if TYPE_CHECKING:
    from ntrp.context.models import SessionState


class RunStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    ERROR = "error"


@dataclass
class RunState:
    run_id: str
    session_id: str
    status: RunStatus = RunStatus.PENDING
    messages: list[dict] = field(default_factory=list)
    usage: Usage = field(default_factory=Usage)
    # Per-tool approval response routing. Each tool that needs approval
    # registers its tool_id → Future and awaits it. The /tools/result
    # endpoint looks up the Future by tool_id and resolves it.
    # Replaces the old single Queue[dict] which forced mutating tools to
    # serialize because they all raced on one shared response stream.
    pending_approvals: dict[str, "asyncio.Future[dict]"] = field(default_factory=dict)
    task: asyncio.Task | None = None
    inject_queue: list[dict] = field(default_factory=list)
    loaded_tools: set[str] = field(default_factory=set)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    cancelled: bool = False
    cancel_terminal_emitted: bool = False
    backgrounded: bool = False
    drain_task: asyncio.Task | None = None
    stop_reason: str | None = None
    # When the run was triggered by a loop, this is the loop's automation
    # task_id. Tools (schedule_wakeup, loop_done) read it to mutate the
    # right loop. None for ordinary user-initiated runs.
    loop_task_id: str | None = None
    # Hidden/meta runs are generated by system events like loop ticks or
    # background-agent completions. The desktop hides their user prompt.
    is_meta_run: bool = False
    # Iteration-mode loops trim prior history to keep the agent's prompt
    # context bounded. The dropped head sits here so saves can re-prepend
    # it — disk history stays complete even though the agent only sees
    # the tail. Empty for non-loop runs and for loop runs under the cap.
    history_prefix: list[dict] = field(default_factory=list)
    # Reference to the live SessionState driving this run. Set during
    # prepare_chat so endpoints (e.g. POST /sessions/{id}/auto) can mutate
    # session-level state (like skip_approvals) without going through a
    # new chat turn. Same object reference shared with the ToolContext.
    session_state: "SessionState | None" = None

    @property
    def pending_injection_count(self) -> int:
        return len(self.inject_queue)

    def queue_injection(self, message: dict) -> None:
        self.inject_queue.append(message)
        self.updated_at = datetime.now(UTC)

    def queue_injections(self, messages: list[dict]) -> None:
        if not messages:
            return
        self.inject_queue.extend(messages)
        self.updated_at = datetime.now(UTC)

    def cancel_injection(self, client_id: str) -> bool:
        for i, entry in enumerate(self.inject_queue):
            if entry.get("client_id") == client_id:
                self.inject_queue.pop(i)
                self.updated_at = datetime.now(UTC)
                return True
        return False

    def drain_injections(self) -> list[dict]:
        if not self.inject_queue:
            return []
        batch = list(self.inject_queue)
        self.inject_queue.clear()
        self.updated_at = datetime.now(UTC)
        return batch

    def get_status(self, now: datetime) -> dict:
        age_seconds = max(0, int((now - self.created_at).total_seconds()))
        idle_seconds = max(0, int((now - self.updated_at).total_seconds()))
        return {
            "run_id": self.run_id,
            "session_id": self.session_id,
            "status": self.status.value,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "age_seconds": age_seconds,
            "idle_seconds": idle_seconds,
            "message_count": len(self.messages),
            "pending_injections": self.pending_injection_count,
            "approvals_pending": len(self.pending_approvals),
            "task_running": self.task is not None and not self.task.done(),
            "drain_task_running": self.drain_task is not None and not self.drain_task.done(),
            "cancelled": self.cancelled,
            "backgrounded": self.backgrounded,
        }


OTID_DEDUP_TTL = timedelta(seconds=30)


class RunRegistry:
    def __init__(self):
        self._runs: dict[str, RunState] = {}
        self._active_by_session: dict[str, str] = {}
        self._bg_registries: dict[str, BackgroundTaskRegistry] = {}
        # `(session_id, client_id) -> (run_id, registered_at)`. A duplicate
        # `/chat/message` POST within OTID_DEDUP_TTL returns the existing
        # run_id instead of starting a second run. Covers network retries
        # and double-clicks; longer-term duplicate guarding is the
        # client's job.
        self._otid_runs: dict[tuple[str, str], tuple[str, datetime]] = {}

    def get_background_registry(self, session_id: str) -> BackgroundTaskRegistry:
        if session_id not in self._bg_registries:
            self._bg_registries[session_id] = BackgroundTaskRegistry(session_id=session_id)
        return self._bg_registries[session_id]

    def create_run(self, session_id: str) -> RunState:
        run_id = generate_slug(2)
        run = RunState(run_id=run_id, session_id=session_id)
        self._runs[run_id] = run
        self._active_by_session[session_id] = run_id
        return run

    @property
    def active_run_count(self) -> int:
        return len(self.list_active_runs())

    def list_active_runs(self) -> list[RunState]:
        active = []
        for session_id in list(self._active_by_session):
            run = self.get_active_run(session_id)
            if run:
                active.append(run)
        return active

    def get_run(self, run_id: str) -> RunState | None:
        return self._runs.get(run_id)

    def get_active_run(self, session_id: str) -> RunState | None:
        run_id = self._active_by_session.get(session_id)
        if not run_id:
            return None
        run = self._runs.get(run_id)
        if run and run.status in (RunStatus.PENDING, RunStatus.RUNNING):
            return run
        self._active_by_session.pop(session_id, None)
        return None

    def get_accepting_run(self, session_id: str) -> RunState | None:
        run = self.get_active_run(session_id)
        if run and not run.cancelled:
            return run
        return None

    def lookup_otid(self, session_id: str, client_id: str) -> RunState | None:
        """Return the run_id a given (session_id, client_id) was last
        registered against, if still within the dedup window."""
        if not client_id:
            return None
        entry = self._otid_runs.get((session_id, client_id))
        if not entry:
            return None
        run_id, registered_at = entry
        if datetime.now(UTC) - registered_at > OTID_DEDUP_TTL:
            self._otid_runs.pop((session_id, client_id), None)
            return None
        return self._runs.get(run_id)

    def register_otid(self, session_id: str, client_id: str, run_id: str) -> None:
        if not client_id:
            return
        self._otid_runs[(session_id, client_id)] = (run_id, datetime.now(UTC))

    def _prune_otids(self, now: datetime) -> None:
        cutoff = now - OTID_DEDUP_TTL
        expired = [key for key, (_, at) in self._otid_runs.items() if at < cutoff]
        for key in expired:
            self._otid_runs.pop(key, None)

    def complete_run(self, run_id: str) -> None:
        run = self._runs.get(run_id)
        if run:
            run.status = RunStatus.COMPLETED
            run.updated_at = datetime.now(UTC)
            if self._active_by_session.get(run.session_id) == run_id:
                self._active_by_session.pop(run.session_id, None)
        self.cleanup_old_runs()

    def cancel_run(self, run_id: str) -> dict[str, bool]:
        run = self._runs.get(run_id)
        if not run:
            return {"found": False, "cancel_requested": False}

        run.cancelled = True
        run.updated_at = datetime.now(UTC)
        is_current = self._active_by_session.get(run.session_id) == run_id

        cancel_requested = False
        if run.task and not run.task.done():
            run.task.cancel()
            cancel_requested = True
        if run.drain_task and not run.drain_task.done():
            run.drain_task.cancel()
            cancel_requested = True

        if is_current:
            registry = self._bg_registries.get(run.session_id)
            if registry:
                for _task_id, _command in registry.cancel_all():
                    cancel_requested = True

        return {"found": True, "cancel_requested": cancel_requested}

    def finish_cancelled(self, run_id: str) -> bool:
        run = self._runs.get(run_id)
        if not run:
            return False

        run.cancelled = True
        run.cancel_terminal_emitted = True
        run.status = RunStatus.CANCELLED
        run.updated_at = datetime.now(UTC)
        if self._active_by_session.get(run.session_id) == run_id:
            self._active_by_session.pop(run.session_id, None)
        self.cleanup_old_runs()
        return True

    async def cancel_all(self, timeout: float = 5.0) -> int:
        tasks = []
        for run in self._runs.values():
            if run.status in (RunStatus.PENDING, RunStatus.RUNNING) and run.task and not run.task.done():
                run.cancelled = True
                run.status = RunStatus.CANCELLED
                run.task.cancel()
                tasks.append(run.task)
            if run.drain_task and not run.drain_task.done():
                run.drain_task.cancel()
                tasks.append(run.drain_task)
        background_cancelled = 0
        for registry in self._bg_registries.values():
            for _task_id, _command in registry.cancel_all():
                background_cancelled += 1
        self._active_by_session.clear()
        if tasks:
            await asyncio.wait(tasks, timeout=timeout)
        return len(tasks) + background_cancelled

    def error_run(self, run_id: str) -> None:
        run = self._runs.get(run_id)
        if run:
            run.status = RunStatus.ERROR
            run.updated_at = datetime.now(UTC)
            if self._active_by_session.get(run.session_id) == run_id:
                self._active_by_session.pop(run.session_id, None)
        self.cleanup_old_runs()

    def cleanup_old_runs(self, max_age_hours: int = 24) -> int:
        now = datetime.now(UTC)
        self._prune_otids(now)
        to_remove = []

        for run_id, run in self._runs.items():
            age = (now - run.updated_at) / timedelta(hours=1)
            if age > max_age_hours and run.status in (RunStatus.COMPLETED, RunStatus.CANCELLED, RunStatus.ERROR):
                to_remove.append(run_id)

        removed_sessions: set[str] = set()
        for run_id in to_remove:
            run = self._runs.pop(run_id, None)
            if run:
                removed_sessions.add(run.session_id)

        for session_id in removed_sessions:
            has_runs = any(r.session_id == session_id for r in self._runs.values())
            if not has_runs:
                self._bg_registries.pop(session_id, None)

        return len(to_remove)

    def get_status(self, now: datetime | None = None) -> dict:
        observed_at = now or datetime.now(UTC)
        active_runs = self.list_active_runs()
        background_task_sessions = [
            {"session_id": session_id, "pending_tasks": registry.pending_count}
            for session_id, registry in sorted(self._bg_registries.items())
            if registry.pending_count
        ]
        return {
            "observed_at": observed_at.isoformat(),
            "total_retained": len(self._runs),
            "active_count": len(active_runs),
            "active_runs": [run.get_status(observed_at) for run in active_runs],
            "background_task_sessions": background_task_sessions,
        }
