from datetime import timedelta

TURN_BUDGET = 50
TOKEN_BUDGET = 8000
IDLE_GAP = timedelta(minutes=10)
TOPIC_SHIFT_THRESHOLD = 0.3
OVERLAP_TURNS = 5
IDLE_SWEEP_INTERVAL = timedelta(seconds=60)
DEDUP_SIMILARITY = 0.93
DEDUP_RECALL_SIMILARITY = 0.80
DEDUP_ADJUDICATE_LIMIT = 5
DEDUP_WINDOW_DAYS = 7
DEDUP_SCAN_LIMIT = 50
